### ISSUE TITLE
not working on retail european games?

### ISSUE THREAD

**Issue by multiyogibear** [thelink2012/novisualrep#3]
I tried to use this with my retail European copy of the NFSU2 and an error message showed up.
"Unsupported game executable.
Please make sure you are using one of the following:
NFS: Underground v1.4 [US] No-CD/Fixed EXE[SPiRiTY]
NFS: Underground 2 v1.2 [ENGLISH] No-CD/Fixed EXE [HOODLUM]

Any solutions?

**Comment by thelink2012** [comment]
Hi. Yes, this plugin patches memory locations. I've used the executable that is most used in general as a base for these addresses. No solution at all. Use the indicated no-CD patch.
