### ISSUE TITLE
Reputation locked at 0 stars, even when fitting parts

### ISSUE THREAD

**Issue by coastercrab** [thelink2012/novisualrep#4]
I can't progress, because I need 1 star for an event, but for some reason I only have 2 bars of rep. This doesn't change if I put custom body parts on my car.

**Comment by thelink2012** [comment]
Could you provide more details? Is this Underground 1? At which event does this occur?

**Comment by coastercrab** [comment]
Sorry for not giving the details, that was dumb of me.
Yes, it's underground 1.
Event 20 is the one that won't let me in.

**Comment by coastercrab** [comment]
I just looked through the script, and I'm guessing the problem is that I'm using an EU exe

**Comment by thelink2012** [comment]
Yeah. I have built this around `NFS: Underground v1.4 [US] No-CD/Fixed EXE [SPiRiTY]`.
